version: 3.0.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
nuget:
  disable_publish_on_pr: true
build_script:
- cmd: >-
    dotnet --version

    dotnet restore ./src/OwinRequestScopeContext/OwinRequestScopeContext.csproj --verbosity m

    dotnet publish ./src/OwinRequestScopeContext/OwinRequestScopeContext.csproj --framework netstandard2.0 --configuration Release /p:IsPublishing="true"

    dotnet publish ./src/OwinRequestScopeContext/OwinRequestScopeContext.csproj --framework net462 --configuration Release /p:IsPublishing="true"
test_script:
- cmd: >-
    dotnet restore ./src/OwinRequestScopeContext.Tests/OwinRequestScopeContext.Tests.csproj --verbosity m

    dotnet test ./src/OwinRequestScopeContext.Tests/OwinRequestScopeContext.Tests.csproj --verbosity m
artifacts:
- path: ./src/OwinRequestScopeContext/bin/Release/netstandard2.0/publish
  name: PublishNetstandard2_0
- path: ./src/OwinRequestScopeContext/bin/Release/net462/publish
  name: PublishNet462
- path: ./src/OwinRequestScopeContext/bin/Packages
  name: Packages
deploy: off